# Twitter Analysis Dataset

In [5]:
import pandas as pd

data = pd.read_csv(r'E:\tvb_25\datasets\Twitter Analysis.csv')
data.head()

,Unnamed: 0,majority_target,statement,BinaryNumTarget,tweet,followers_count,friends_count,favourites_count,statuses_count,listed_count,...,determiners,conjunctions,dots,exclamation,questions,ampersand,capitals,digits,long_word_freq,short_word_freq
0,0,True,End of eviction moratorium means millions of A...,1.0,@POTUS Biden Blunders - 6 Month Update\n\nInfl...,4262.0,3619.0,34945.0,16423.0,44.0,...,0,0,5,0,1,0,33,3,5,19
1,1,True,End of eviction moratorium means millions of A...,1.0,@S0SickRick @Stairmaster_ @6d6f636869 Not as m...,1393.0,1621.0,31436.0,37184.0,64.0,...,0,2,1,0,0,0,14,0,2,34
2,2,True,End of eviction moratorium means millions of A...,1.0,THE SUPREME COURT is siding with super rich pr...,9.0,84.0,219.0,1184.0,0.0,...,0,1,0,0,0,0,3,0,4,10
3,3,True,End of eviction moratorium means millions of A...,1.0,@POTUS Biden Blunders\n\nBroken campaign promi...,4262.0,3619.0,34945.0,16423.0,44.0,...,0,1,3,0,0,1,6,8,1,30
4,4,True,End of eviction moratorium means millions of A...,1.0,@OhComfy I agree. The confluence of events rig...,70.0,166.0,15282.0,2194.0,0.0,...,0,1,3,0,1,0,11,3,2,19

In [8]:
# Turn it into a dataframe so it's easier to work with

df = pd.DataFrame(data)
df.head()

,Unnamed: 0,majority_target,statement,BinaryNumTarget,tweet,followers_count,friends_count,favourites_count,statuses_count,listed_count,...,determiners,conjunctions,dots,exclamation,questions,ampersand,capitals,digits,long_word_freq,short_word_freq
0,0,True,End of eviction moratorium means millions of A...,1.0,@POTUS Biden Blunders - 6 Month Update\n\nInfl...,4262.0,3619.0,34945.0,16423.0,44.0,...,0,0,5,0,1,0,33,3,5,19
1,1,True,End of eviction moratorium means millions of A...,1.0,@S0SickRick @Stairmaster_ @6d6f636869 Not as m...,1393.0,1621.0,31436.0,37184.0,64.0,...,0,2,1,0,0,0,14,0,2,34
2,2,True,End of eviction moratorium means millions of A...,1.0,THE SUPREME COURT is siding with super rich pr...,9.0,84.0,219.0,1184.0,0.0,...,0,1,0,0,0,0,3,0,4,10
3,3,True,End of eviction moratorium means millions of A...,1.0,@POTUS Biden Blunders\n\nBroken campaign promi...,4262.0,3619.0,34945.0,16423.0,44.0,...,0,1,3,0,0,1,6,8,1,30
4,4,True,End of eviction moratorium means millions of A...,1.0,@OhComfy I agree. The confluence of events rig...,70.0,166.0,15282.0,2194.0,0.0,...,0,1,3,0,1,0,11,3,2,19

## Basic data exploration

In [10]:
df.shape
# 134,198 rows
# 64 columns

(134198, 64)

In [11]:
# Checking for missing values
df.isnull().sum()

Unnamed: 0         0
majority_target    0
statement          0
BinaryNumTarget    0
tweet              0
                  ..
ampersand          0
capitals           0
digits             0
long_word_freq     0
short_word_freq    0
Length: 64, dtype: int64

In [13]:
# Descriptive statistics
df.describe()

,Unnamed: 0,BinaryNumTarget,followers_count,friends_count,favourites_count,statuses_count,listed_count,following,BotScore,BotScoreBinary,...,determiners,conjunctions,dots,exclamation,questions,ampersand,capitals,digits,long_word_freq,short_word_freq
count,134198.00000,134198.000000,1.341980e+05,134198.000000,1.341980e+05,1.341980e+05,134198.000000,134198.0,134198.000000,134198.000000,...,134198.000000,134198.000000,134198.000000,134198.000000,134198.000000,134198.000000,134198.000000,134198.000000,134198.000000,134198.000000
mean,67098.50000,0.513644,1.129308e+04,1893.454455,3.298123e+04,3.419576e+04,73.300198,0.0,0.059106,0.032355,...,0.135583,1.003495,2.366116,0.259408,0.307151,0.121537,12.831905,3.559494,2.249557,21.438658
std,38739.77005,0.499816,4.374971e+05,6997.695671,6.878021e+04,7.510120e+04,1083.274277,0.0,0.167819,0.176942,...,0.379235,1.086844,2.140459,0.903957,0.774367,0.453865,15.557524,6.674458,2.912136,9.625147
min,0.00000,0.000000,0.000000e+00,0.000000,0.000000e+00,1.000000e+00,0.000000,0.0,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,33549.25000,0.000000,7.000000e+01,168.000000,1.356000e+03,3.046000e+03,0.000000,0.0,0.030000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,6.000000,0.000000,1.000000,14.000000
50%,67098.50000,1.000000,3.540000e+02,567.000000,8.377000e+03,1.101900e+04,2.000000,0.0,0.030000,0.000000,...,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,10.000000,2.000000,2.000000,21.000000
75%,100647.75000,1.000000,1.573000e+03,1726.000000,3.352650e+04,3.357375e+04,11.000000,0.0,0.030000,0.000000,...,0.000000,2.000000,3.000000,0.000000,0.000000,0.000000,15.000000,4.000000,3.000000,28.000000
max,134197.00000,1.000000,1.306019e+08,586901.000000,1.765080e+06,2.958918e+06,222193.000000,0.0,1.000000,1.000000,...,5.000000,13.000000,50.000000,66.000000,43.000000,13.000000,250.000000,138.000000,47.000000,164.000000

In [15]:
df.info

<bound method DataFrame.info of         Unnamed: 0  majority_target  \
0                0             True
1                1             True
2                2             True
3                3             True
4                4             True
...            ...              ...
134193      134193            False
134194      134194            False
134195      134195            False
134196      134196            False
134197      134197            False

                                                statement  BinaryNumTarget  \
0       End of eviction moratorium means millions of A...              1.0
1       End of eviction moratorium means millions of A...              1.0
2       End of eviction moratorium means millions of A...              1.0
3       End of eviction moratorium means millions of A...              1.0
4       End of eviction moratorium means millions of A...              1.0
...                                                   ...              ...
134193  Joe Bidens great-grandfather Joseph J. Biden w...              0.0
134194  Joe Bidens great-grandfather Joseph J. Biden w...              0.0
134195  Joe Bidens great-grandfather Joseph J. Biden w...              0.0
134196  Joe Bidens great-grandfather Joseph J. Biden w...              0.0
134197  Joe Bidens great-grandfather Joseph J. Biden w...              0.0

                                                    tweet  followers_count  \
0       @POTUS Biden Blunders - 6 Month Update\n\nInfl...           4262.0
1       @S0SickRick @Stairmaster_ @6d6f636869 Not as m...           1393.0
2       THE SUPREME COURT is siding with super rich pr...              9.0
3       @POTUS Biden Blunders\n\nBroken campaign promi...           4262.0
4       @OhComfy I agree. The confluence of events rig...             70.0
...                                                   ...              ...
134193  Joe Biden's family owned African slaves....\n\...           2075.0
134194  Joe Bidens great, great grandfather was a slav...           1636.0
134195  @ChevyChaseToGo "Joe Bidens great-grandfather ...            286.0
134196  @JoeBiden Facts are Bidens VP Kamala Harris Gr...              2.0
134197  @sunny Yes representation matters. Did you kno...            178.0

        friends_count  favourites_count  statuses_count  listed_count  ...  \
0              3619.0           34945.0         16423.0          44.0  ...
1              1621.0           31436.0         37184.0          64.0  ...
2                84.0             219.0          1184.0           0.0  ...
3              3619.0           34945.0         16423.0          44.0  ...
4               166.0           15282.0          2194.0           0.0  ...
...               ...               ...             ...           ...  ...
134193         2662.0          156306.0         62375.0           3.0  ...
134194         1626.0          215290.0         44011.0          10.0  ...
134195         2501.0           28377.0          7617.0           1.0  ...
134196           45.0              16.0           509.0           0.0  ...
134197          471.0            1254.0          2094.0           0.0  ...

        determiners conjunctions  dots  exclamation  questions  ampersand  \
0                 0            0     5            0          1          0
1                 0            2     1            0          0          0
2                 0            1     0            0          0          0
3                 0            1     3            0          0          1
4                 0            1     3            0          1          0
...             ...          ...   ...          ...        ...        ...
134193            0            2     1            0          3          0
134194            0            0     1            0          0          0
134195            1            4     1            0          0          1
134196            1            0     3            0          0          0
134197            0            1     2            0          1          0

        capitals  digits  long_word_freq  short_word_freq
0             33       3               5               19
1             14       0               2               34
2              3       0               4               10
3              6       8               1               30
4             11       3               2               19
...          ...     ...             ...              ...
134193        31       0               4               32
134194        16       6               2                8
134195         2       4               0               37
134196         0       0               1               11
134197         6       0               0               30

[134198 rows x 64 columns]>